package _1MoreAboutOperationsOnCollections

import java.util.*

fun main(args: Array<String>) {
    val list = listOf(1, 2, 3, 4, 5)

    list.filter { it % 2 == 1 }                 // [1, 3, 5]
    // this method is inlined

//    val destination = ArrayList<Int>()
//    for (element in list) if (element % 2 == 1) destination.add(element)
//    return destination
//    inlining: generated by the compiler
//    receiver(this) -> list
//    predicate(element) -> element % 2 == 1

    list.filter { it % 2 == 1 }.map { it * 2 }  // [1, 9 25]
    // eager evaluation
    // intermediate collection is created
}

/*
inline fun <T> Iterable<T>.filter(predicate: (T) -> Boolean): List<T> {
    val destination = ArrayList<T>()
    for (element in this) if (predicate(element)) destination.add(element)
    return destination
}
*/
